name: savvy
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.0
  flutter_svg: ^2.0.17
  smooth_page_indicator: ^1.2.1
  pin_code_fields: ^8.0.1
  email_validator: ^3.0.0
  supabase_flutter: ^2.8.4 
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.0.0
  animated_text_kit: ^4.2.3
  timezone: ^0.10.0
  permission_handler: ^12.0.0+1
  http: ^1.3.0
  intl: ^0.18.0
  flutter_riverpod: ^2.4.9
  mailer: ^6.4.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"
  flutter_native_splash: ^2.3.10 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "#FFFFFF" # Optional for adaptive icons
  adaptive_icon_foreground: "assets/icons/logo.png" # Ensure a high-res foreground
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/icons/logo.png"
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/logo.png"

flutter_native_splash:
  color: "#3A9CEB" # Background color
  image: assets/icons/splash.png # Use PNG (Android 12+ requires PNG)
  
  android: true
  ios: true
  fullscreen: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill
  
  android_12:
    color: "#3A9CEB"
    image: assets/icons/splash.png
    icon_background_color: "#3A9CEB"

flutter:
  uses-material-design: true
  assets:
    - assets/images/trend.svg
    - assets/icons/splash.png
    - assets/images/saving.png
    - assets/images/bank-card.png
    - assets/icons/google.svg
    - assets/icons/facebook.svg
    - assets/images/profile.jpg
    - assets/animation/robot.gif
    # - assets/categories_icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600